package tim1.backend.soap.ZalbaNaOdluku;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:23:33.359+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ZalbaNaOdlukuService", 
                  wsdlLocation = "classpath:wsdl/ZalbaNaOdluku.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/zalba-na-odluku") 
public class ZalbaNaOdlukuService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/zalba-na-odluku", "ZalbaNaOdlukuService");
    public final static QName ZalbaNaOdlukuServiceSoapBinding = new QName("http://www.ftn.uns.ac.rs/zalba-na-odluku", "ZalbaNaOdlukuServiceSoapBinding");
    static {
        URL url = ZalbaNaOdlukuService.class.getClassLoader().getResource("wsdl/ZalbaNaOdluku.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZalbaNaOdlukuService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/ZalbaNaOdluku.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ZalbaNaOdlukuService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZalbaNaOdlukuService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZalbaNaOdlukuService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZalbaNaOdlukuService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZalbaNaOdlukuService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZalbaNaOdlukuService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZalbaNaOdlukuServicePortType
     */
    @WebEndpoint(name = "ZalbaNaOdlukuServiceSoapBinding")
    public ZalbaNaOdlukuServicePortType getZalbaNaOdlukuServiceSoapBinding() {
        return super.getPort(ZalbaNaOdlukuServiceSoapBinding, ZalbaNaOdlukuServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZalbaNaOdlukuServicePortType
     */
    @WebEndpoint(name = "ZalbaNaOdlukuServiceSoapBinding")
    public ZalbaNaOdlukuServicePortType getZalbaNaOdlukuServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZalbaNaOdlukuServiceSoapBinding, ZalbaNaOdlukuServicePortType.class, features);
    }

}
