
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim1.backend.soap.ZalbaNaOdluku;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T15:54:02.781+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZalbaNaOdlukuService",
                      portName = "ZalbaNaOdlukuServiceSoapBinding",
                      targetNamespace = "http://www.ftn.uns.ac.rs/zalba-na-odluku",
                      wsdlLocation = "classpath:wsdl/ZalbaNaOdluku.wsdl",
                      endpointInterface = "tim1.backend.soap.ZalbaNaOdluku.ZalbaNaOdlukuServicePortType")
                      
public class ZalbaNaOdlukuServiceSoapBindingImpl implements ZalbaNaOdlukuServicePortType {

    private static final Logger LOG = Logger.getLogger(ZalbaNaOdlukuServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.zalba_na_odluku.ZalbaNaOdlukuServicePortType#getZalbaNaOdlukuById(java.lang.String id)*
     */
    public java.lang.String getZalbaNaOdlukuById(java.lang.String id) { 
        LOG.info("Executing operation getZalbaNaOdlukuById");
        System.out.println(id);
        try {
            java.lang.String _return = "asdkfljdsaflkhdsaflkjdshf";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
