package tim1.backend.soap.ZalbaNaOdluku;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:23:33.352+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/zalba-na-odluku", name = "ZalbaNaOdlukuServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZalbaNaOdlukuServicePortType {

    @WebMethod(action = "http://www.zalbanaodluku.com/ws/getZalbaNaOdlukuById")
    @WebResult(name = "zalba_odluka", targetNamespace = "", partName = "zalba_odluka")
    public TZalbaNaOdluku getZalbaNaOdlukuById(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        java.lang.String id
    );
}
