
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim1.backend.soap.ZalbaNaOdluku;

import java.io.StringReader;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.xmldb.api.modules.XMLResource;

import tim1.backend.service.ZalbaNaOdlukuService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:23:33.292+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZalbaNaOdlukuService",
                      portName = "ZalbaNaOdlukuServiceSoapBinding",
                      targetNamespace = "http://www.ftn.uns.ac.rs/zalba-na-odluku",
                      wsdlLocation = "classpath:wsdl/ZalbaNaOdluku.wsdl",
                      endpointInterface = "tim1.backend.soap.ZalbaNaOdluku.ZalbaNaOdlukuServicePortType")
                      
public class ZalbaNaOdlukuServiceSoapBindingImpl implements ZalbaNaOdlukuServicePortType {

    @Autowired
    ZalbaNaOdlukuService zalbaNaOdlukuService;

    private static final Logger LOG = Logger.getLogger(ZalbaNaOdlukuServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.zalba_na_odluku.ZalbaNaOdlukuServicePortType#getZalbaNaOdlukuById(java.lang.String id)*
     */
    public TZalbaNaOdluku getZalbaNaOdlukuById(java.lang.String id) { 
        LOG.info("Executing operation getZalbaNaOdlukuById");
        System.out.println(id);

        try {
            String documentId = id; 
            JAXBContext context = JAXBContext.newInstance(TZalbaNaOdluku.class);
            Unmarshaller unmarshaller = context.createUnmarshaller();
            XMLResource document = zalbaNaOdlukuService.readXML(documentId);
            String s = document.getContent().toString();
            StringReader reader = new StringReader(s);
            TZalbaNaOdluku zalba = (TZalbaNaOdluku) unmarshaller.unmarshal(reader);
            return zalba;
            // TZalbaNaOdluku _return = null;
            // return _return;
        } 
        catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
