//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 06:46:47 PM CET 
//


package tim1.backend.model.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Osnovni_podaci"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Organ"/&amp;gt;
 *                   &amp;lt;element name="Broj_predmeta"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&amp;gt;
 *                         &amp;lt;minInclusive value="0"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="Datum"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
 *                           &amp;lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Podnosioc_zahteva"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="Sadrzaj"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *                   &amp;lt;element name="Podnaslov" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *                   &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Paragraf"/&amp;gt;
 *                   &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Dostavljeno"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "osnovniPodaci",
    "sadrzaj"
})
@XmlRootElement(name = "Obavestenje")
public class Obavestenje {

    @XmlElement(name = "Osnovni_podaci", required = true)
    protected Obavestenje.OsnovniPodaci osnovniPodaci;
    @XmlElement(name = "Sadrzaj", required = true)
    protected Obavestenje.Sadrzaj sadrzaj;

    /**
     * Gets the value of the osnovniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.OsnovniPodaci }
     *     
     */
    public Obavestenje.OsnovniPodaci getOsnovniPodaci() {
        return osnovniPodaci;
    }

    /**
     * Sets the value of the osnovniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.OsnovniPodaci }
     *     
     */
    public void setOsnovniPodaci(Obavestenje.OsnovniPodaci value) {
        this.osnovniPodaci = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.Sadrzaj }
     *     
     */
    public Obavestenje.Sadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.Sadrzaj }
     *     
     */
    public void setSadrzaj(Obavestenje.Sadrzaj value) {
        this.sadrzaj = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Organ"/&amp;gt;
     *         &amp;lt;element name="Broj_predmeta"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&amp;gt;
     *               &amp;lt;minInclusive value="0"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="Datum"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
     *                 &amp;lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Podnosioc_zahteva"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organ",
        "brojPredmeta",
        "datum",
        "podnosiocZahteva"
    })
    public static class OsnovniPodaci {

        @XmlElement(name = "Organ", required = true)
        protected Organ organ;
        @XmlElement(name = "Broj_predmeta")
        protected int brojPredmeta;
        @XmlElement(name = "Datum", required = true)
        protected Obavestenje.OsnovniPodaci.Datum datum;
        @XmlElement(name = "Podnosioc_zahteva", required = true)
        protected PodnosiocZahteva podnosiocZahteva;

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link Organ }
         *     
         */
        public Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link Organ }
         *     
         */
        public void setOrgan(Organ value) {
            this.organ = value;
        }

        /**
         * Gets the value of the brojPredmeta property.
         * 
         */
        public int getBrojPredmeta() {
            return brojPredmeta;
        }

        /**
         * Sets the value of the brojPredmeta property.
         * 
         */
        public void setBrojPredmeta(int value) {
            this.brojPredmeta = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.OsnovniPodaci.Datum }
         *     
         */
        public Obavestenje.OsnovniPodaci.Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.OsnovniPodaci.Datum }
         *     
         */
        public void setDatum(Obavestenje.OsnovniPodaci.Datum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the podnosiocZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link PodnosiocZahteva }
         *     
         */
        public PodnosiocZahteva getPodnosiocZahteva() {
            return podnosiocZahteva;
        }

        /**
         * Sets the value of the podnosiocZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link PodnosiocZahteva }
         *     
         */
        public void setPodnosiocZahteva(PodnosiocZahteva value) {
            this.podnosiocZahteva = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
         *       &amp;lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *       &amp;lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Datum {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "property")
            protected String property;
            @XmlAttribute(name = "datatype")
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                return property;
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
     *         &amp;lt;element name="Podnaslov" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
     *         &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Paragraf"/&amp;gt;
     *         &amp;lt;element ref="{http://www.ftn.uns.ac.rs/obavestenjecir}Dostavljeno"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "podnaslov",
        "paragraf",
        "dostavljeno"
    })
    public static class Sadrzaj {

        @XmlElement(name = "Naslov", required = true)
        protected String naslov;
        @XmlElement(name = "Podnaslov", required = true)
        protected String podnaslov;
        @XmlElement(name = "Paragraf", required = true)
        protected Paragraf paragraf;
        @XmlElement(name = "Dostavljeno", required = true)
        protected Select dostavljeno;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the podnaslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnaslov() {
            return podnaslov;
        }

        /**
         * Sets the value of the podnaslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnaslov(String value) {
            this.podnaslov = value;
        }

        /**
         * Gets the value of the paragraf property.
         * 
         * @return
         *     possible object is
         *     {@link Paragraf }
         *     
         */
        public Paragraf getParagraf() {
            return paragraf;
        }

        /**
         * Sets the value of the paragraf property.
         * 
         * @param value
         *     allowed object is
         *     {@link Paragraf }
         *     
         */
        public void setParagraf(Paragraf value) {
            this.paragraf = value;
        }

        /**
         * Gets the value of the dostavljeno property.
         * 
         * @return
         *     possible object is
         *     {@link Select }
         *     
         */
        public Select getDostavljeno() {
            return dostavljeno;
        }

        /**
         * Sets the value of the dostavljeno property.
         * 
         * @param value
         *     allowed object is
         *     {@link Select }
         *     
         */
        public void setDostavljeno(Select value) {
            this.dostavljeno = value;
        }

    }

}
