
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim1.backend.soap.hello;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlSeeAlso;

import tim1.backend.soap.hello.types.ObjectFactory;
import tim1.backend.soap.hello.types.RequestMissType;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T20:09:59.425+01:00
 * Generated source version: 3.2.1
 * 
 */


@WebService(serviceName = "HelloDocumentService",
			portName = "HelloDocumentPort",
			targetNamespace = "http://soap.spring.com/ws/hello",
			endpointInterface = "tim1.backend.soap.hello.HelloDocument")
                      
public class HelloDocumentImpl implements HelloDocument {

    private static final Logger LOG = Logger.getLogger(HelloDocumentImpl.class.getName());

    /* (non-Javadoc)
     * @see com.spring.soap.ws.hello.HelloDocument#sayHelloMiss(com.spring.soap.ws.hello.types.RequestMissType requestMiss)*
     */
	public java.lang.String sayHelloMiss(RequestMissType requestMiss) {
		LOG.info("Executing operation sayHelloMiss");
		System.out.println(requestMiss);
		
		ObjectFactory helloFactory = new ObjectFactory();
		JAXBElement<String> response = helloFactory.createResponseMiss("Hello miss" + requestMiss.getFirstName() + " " + requestMiss.getLastName());
		return response.getValue();
	}

}
