//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 10:47:47 AM CET 
//


package tim1.backend.model.zahtev;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tip_zahteva" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacini_slanja" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tekst" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="selektovan" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="rb" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipZahteva"
})
@XmlRootElement(name = "tipovi_zahteva")
public class TipoviZahteva {

    @XmlElement(name = "tip_zahteva", required = true)
    protected List<TipoviZahteva.TipZahteva> tipZahteva;

    /**
     * Gets the value of the tipZahteva property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipZahteva property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipZahteva().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoviZahteva.TipZahteva }
     * 
     * 
     */
    public List<TipoviZahteva.TipZahteva> getTipZahteva() {
        if (tipZahteva == null) {
            tipZahteva = new ArrayList<TipoviZahteva.TipZahteva>();
        }
        return this.tipZahteva;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacini_slanja" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="tekst" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="selektovan" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="rb" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naciniSlanja"
    })
    public static class TipZahteva {

        @XmlElement(name = "nacini_slanja")
        protected List<NaciniSlanja> naciniSlanja;
        @XmlAttribute(name = "tekst")
        protected String tekst;
        @XmlAttribute(name = "selektovan")
        protected Boolean selektovan;
        @XmlAttribute(name = "rb")
        @XmlSchemaType(name = "anySimpleType")
        protected String rb;

        /**
         * Gets the value of the naciniSlanja property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the naciniSlanja property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNaciniSlanja().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NaciniSlanja }
         * 
         * 
         */
        public List<NaciniSlanja> getNaciniSlanja() {
            if (naciniSlanja == null) {
                naciniSlanja = new ArrayList<NaciniSlanja>();
            }
            return this.naciniSlanja;
        }

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekst(String value) {
            this.tekst = value;
        }

        /**
         * Gets the value of the selektovan property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSelektovan() {
            if (selektovan == null) {
                return false;
            } else {
                return selektovan;
            }
        }

        /**
         * Sets the value of the selektovan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSelektovan(Boolean value) {
            this.selektovan = value;
        }

        /**
         * Gets the value of the rb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRb() {
            return rb;
        }

        /**
         * Sets the value of the rb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRb(String value) {
            this.rb = value;
        }

    }

}
