//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 12:34:07 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://www.ftn.uns.ac.rs/zalba-na-cutanje", 
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns = {
        @XmlNs(prefix = "pred", namespaceURI = "http://www.ftn.uns.ac.rs/rdf/examples/predicate/")
    })
package tim1.sluzbenik.model.zalbacutanje;

import javax.xml.bind.annotation.XmlNs;
