package tim1.email.soap.Email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-04T11:27:56.129+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/email", name = "EmailServicePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmailServicePortType {

    @WebMethod(action = "http://www.ftn.uns.ac.rs/email/ws/sendEmail")
    @WebResult(name = "statusSlanja", targetNamespace = "", partName = "statusSlanja")
    public java.lang.String sendEmail(
        @WebParam(partName = "to", name = "to", targetNamespace = "")
        java.lang.String to,
        @WebParam(partName = "subject", name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(partName = "content", name = "content", targetNamespace = "")
        java.lang.String content,
        @WebParam(partName = "pdfPath", name = "pdfPath", targetNamespace = "")
        java.lang.String pdfPath,
        @WebParam(partName = "htmlPath", name = "htmlPath", targetNamespace = "")
        java.lang.String htmlPath
    );
}
