package tim1.sluzbenik.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T16:13:12.031+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/zalba-na-odluku", name = "ZalbaNaOdlukuServicePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZalbaNaOdlukuServicePortType {

    @WebMethod(action = "http://www.zalbanaodluku.com/ws/getAll")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public java.lang.String getAll();

    @WebMethod(action = "http://www.zalbanaodluku.com/ws/getZalbaNaOdlukuById")
    @WebResult(name = "zalba_odluka", targetNamespace = "", partName = "zalba_odluka")
    public java.lang.String getZalbaNaOdlukuById(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        java.lang.String id
    );
}
