//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 03:19:53 PM CET 
//


package tim1.backend.model.izvestaj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="resenja" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sviZahtevi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="odbijeniZahtevi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="odobreniZahtevi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sveZalbe" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="zalbeNaOdluku" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="zalbeNaCutanje" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Izvestaj")
public class Izvestaj {

    @XmlAttribute(name = "resenja")
    protected Integer resenja;
    @XmlAttribute(name = "sviZahtevi")
    protected Integer sviZahtevi;
    @XmlAttribute(name = "odbijeniZahtevi")
    protected Integer odbijeniZahtevi;
    @XmlAttribute(name = "odobreniZahtevi")
    protected Integer odobreniZahtevi;
    @XmlAttribute(name = "sveZalbe")
    protected Integer sveZalbe;
    @XmlAttribute(name = "zalbeNaOdluku")
    protected Integer zalbeNaOdluku;
    @XmlAttribute(name = "zalbeNaCutanje")
    protected Integer zalbeNaCutanje;

    /**
     * Gets the value of the resenja property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResenja() {
        return resenja;
    }

    /**
     * Sets the value of the resenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResenja(Integer value) {
        this.resenja = value;
    }

    /**
     * Gets the value of the sviZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSviZahtevi() {
        return sviZahtevi;
    }

    /**
     * Sets the value of the sviZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSviZahtevi(Integer value) {
        this.sviZahtevi = value;
    }

    /**
     * Gets the value of the odbijeniZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOdbijeniZahtevi() {
        return odbijeniZahtevi;
    }

    /**
     * Sets the value of the odbijeniZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOdbijeniZahtevi(Integer value) {
        this.odbijeniZahtevi = value;
    }

    /**
     * Gets the value of the odobreniZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOdobreniZahtevi() {
        return odobreniZahtevi;
    }

    /**
     * Sets the value of the odobreniZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOdobreniZahtevi(Integer value) {
        this.odobreniZahtevi = value;
    }

    /**
     * Gets the value of the sveZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSveZalbe() {
        return sveZalbe;
    }

    /**
     * Sets the value of the sveZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSveZalbe(Integer value) {
        this.sveZalbe = value;
    }

    /**
     * Gets the value of the zalbeNaOdluku property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getZalbeNaOdluku() {
        return zalbeNaOdluku;
    }

    /**
     * Sets the value of the zalbeNaOdluku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setZalbeNaOdluku(Integer value) {
        this.zalbeNaOdluku = value;
    }

    /**
     * Gets the value of the zalbeNaCutanje property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getZalbeNaCutanje() {
        return zalbeNaCutanje;
    }

    /**
     * Sets the value of the zalbeNaCutanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setZalbeNaCutanje(Integer value) {
        this.zalbeNaCutanje = value;
    }

}
