
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim1.backend.soap.Resenje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.stereotype.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-04T17:37:52.870+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "http://www.ftn.uns.ac.rs/resenje",
                      wsdlLocation = "classpath:wsdl/Resenje.wsdl",
                      endpointInterface = "tim1.backend.soap.Resenje.ResenjeServicePortType")
@Service       
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.resenje.ResenjeServicePortType#getResenjeById(java.lang.String id)*
     */
    public java.lang.String getResenjeById(java.lang.String id) { 
        LOG.info("Executing operation getResenjeById");
        System.out.println(id);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.resenje.ResenjeServicePortType#getAll()*
     */
    public java.lang.String getAll() { 
        LOG.info("Executing operation getAll");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
