
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim1.backend.soap.Resenje;

import java.io.ByteArrayOutputStream;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.xmldb.api.modules.XMLResource;

import tim1.backend.model.liste.JaxbLista;
import tim1.backend.model.resenje.Resenje;
import tim1.backend.service.ResenjeService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-04T17:37:52.870+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "http://www.ftn.uns.ac.rs/resenje",
                      wsdlLocation = "classpath:wsdl/Resenje.wsdl",
                      endpointInterface = "tim1.backend.soap.Resenje.ResenjeServicePortType")
@Service       
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    @Autowired
    private ResenjeService resenjeService;
    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());

    public java.lang.String getAll() { 
        LOG.info("Executing operation getAll");
        try {
            JaxbLista<Resenje> lista = resenjeService.findAllFromCollection();
            JAXBContext context = JAXBContext.newInstance(JaxbLista.class);
            Marshaller marshaller = context.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
        
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            marshaller.marshal(lista, stream);
            String listaString = new String(stream.toByteArray());
            return listaString;
            
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public java.lang.String getResenjeById(java.lang.String id) { 
        LOG.info("Executing operation getResenjeById");
  
        try {
            String documentId = id;
            XMLResource xml = resenjeService.readXML(documentId);
            return xml.getContent().toString();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
